#!/usr/bin/env bash
echo removing any old files in dist/* ...
setopt rmstarsilent & rm -f dist/*
echo creating sdist ...
python3 setup.py sdist
echo uploading to PyPi using twine ...
python3 -m twine upload dist/*
echo done
